// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcx1DD10nIppERYSRQs3yCjgM-wUOfcE4',
    appId: '1:73057088889:web:c47c5941fd0007a9a26ba8',
    messagingSenderId: '73057088889',
    projectId: 'firedata-d6bd1',
    authDomain: 'firedata-d6bd1.firebaseapp.com',
    storageBucket: 'firedata-d6bd1.appspot.com',
    measurementId: 'G-X2074HGRMX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpVAGTuTKRUtV-WAhIaXaqS2mktl09KoQ',
    appId: '1:73057088889:android:eb3f02969e5bff19a26ba8',
    messagingSenderId: '73057088889',
    projectId: 'firedata-d6bd1',
    storageBucket: 'firedata-d6bd1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS-6Dz1clanMMTDp6u-wlGiMvmCnijRLQ',
    appId: '1:73057088889:ios:7555709c9411ba13a26ba8',
    messagingSenderId: '73057088889',
    projectId: 'firedata-d6bd1',
    storageBucket: 'firedata-d6bd1.appspot.com',
    iosClientId: '73057088889-r0fd1s8q3n007gj3dnseaj58ottr86gc.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBS-6Dz1clanMMTDp6u-wlGiMvmCnijRLQ',
    appId: '1:73057088889:ios:7555709c9411ba13a26ba8',
    messagingSenderId: '73057088889',
    projectId: 'firedata-d6bd1',
    storageBucket: 'firedata-d6bd1.appspot.com',
    iosClientId: '73057088889-r0fd1s8q3n007gj3dnseaj58ottr86gc.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
